// src/app/homepage/Homepage.tsx
/*
SPDX-Copyright: Copyright (c) Capital One Services,LLC 
SPDX-License-Identifier: Apache-2.0

Copyright 2018 Capital One Services, LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 */

import {useEffect, useRef, useState} from 'react';
import {useConfigurationService} from '../core/services-context';
import {ConfigModel} from '../models/config.model';
import {ModifierEnum} from '../models/modifier.enum';
import {OptionsModel, OptionsModelKeys} from '../models/options.model';
import {sanitizeUrl} from './sanitize-url';
import './homepage.scss';

const MODIFIER_LABELS: Record<ModifierEnum, string> = {
    [ModifierEnum.dbl_click]: 'Only Double Click',
    [ModifierEnum.ctrl_dbl_click]: 'Ctrl + Double Click',
    [ModifierEnum.alt_dbl_click]: 'Alt + Double Click',
    [ModifierEnum.meta_dbl_click]: 'Command + Double Click',
    [ModifierEnum.ctrl_alt_dbl_click]: 'Ctrl + Alt + Double Click',
};

const SAVING_SPINNER_DELAY = 2000;

export function Homepage() {
    const configurationService = useConfigurationService();
    const [config, setConfig] = useState<ConfigModel>();
    const [extensionVersion, setExtensionVersion] = useState('');
    const [options, setOptions] = useState<OptionsModel>(new OptionsModel());
    const [savingOptions, setSavingOptions] = useState(false);
    const [optionsSaved, setOptionsSaved] = useState(false);
    const savingTimer = useRef<ReturnType<typeof setTimeout>>(undefined);

    useEffect(() => {
        configurationService.getConfiguration().then(setConfig);
        configurationService.getExtensionVersion().then(setExtensionVersion);
        chrome.storage.local.get(OptionsModelKeys, (result: Partial<OptionsModel>) => {
            setOptions(new OptionsModel(result));
        });
    }, [configurationService]);

    useEffect(() => () => clearTimeout(savingTimer.current), []);

    const optionsChanged = () => {
        setOptionsSaved(false);
        setSavingOptions(false);
    };

    const updateOptions = (changes: Partial<OptionsModel>) => {
        setOptions(current => new OptionsModel({...current, ...changes}));
        optionsChanged();
    };

    const saveOptions = () => {
        setOptionsSaved(false);
        setSavingOptions(true);
        /* Unknown issue where the callback is extremely slow even after changes have been
         * picked up by the content-script, sometimes the callback is not fired at all, so
         * the spinner below is faked instead of driven by it.
         */
        chrome.storage.local.set(options, () => {
        });
        clearTimeout(savingTimer.current);
        savingTimer.current = setTimeout(() => {
            setSavingOptions(false);
            setOptionsSaved(true);
        }, SAVING_SPINNER_DELAY);
    };

    const slackChannelNativeUrl = sanitizeUrl(config?.slackChannelLink);

    return (
        <div id="decoderOptions">
            <div id="optionsContainer">
                <div className="text-center">
                    <img id="icon" className="logo" src={config?.mainIconPath}/>

                    <p id="version">v{extensionVersion}</p>
                </div>
                <div className="options-box">
                    <div className="options-info">
                        <p>
                            Your input makes Acronym Decoder smarter! Please send feedback on wrong/missing definitions
                            or this tool in general to{' '}
                            <a href={`mailto:${config?.contactEmail ?? ''}`}>{config?.contactEmail}</a>
                        </p>
                        <p>
                            For more info on Acronym Decoder and how to use it, visit our{' '}
                            <a href={sanitizeUrl(config?.extensionInfoPageLink)} target="_blank"
                               rel="noopener noreferrer">
                                {config?.extensionInfoPageName}
                            </a>
                            {' '}or join our Slack channel{' '}
                            <a href={slackChannelNativeUrl}>
                                {config?.slackChannelName}
                            </a>
                        </p>
                    </div>
                    <hr/>
                    <h4>Options</h4>
                    <hr/>
                    <div className="d-flex flex-row justify-content-evenly align-items-center">
                        <h6 className="w-50">On page lookup:</h6>
                        <select className="form-select w-50" aria-label="On page lookup"
                                value={String(options.lookupEnabled)}
                                onChange={event => updateOptions({lookupEnabled: event.target.value === 'true'})}>
                            <option value="true">Enabled</option>
                            <option value="false">Disabled</option>
                        </select>
                    </div>
                    <div className="d-flex flex-row justify-content-evenly align-items-center">
                        <h6 className="w-50">Mouse click modifier:</h6>
                        <select className="form-select w-50" aria-label="Mouse click modifier"
                                value={String(options.lookupModifier)}
                                onChange={event => updateOptions({lookupModifier: Number(event.target.value)})}>
                            {Object.entries(MODIFIER_LABELS).map(([modifier, label]) => (
                                <option key={modifier} value={modifier}>{label}</option>
                            ))}
                        </select>
                    </div>
                    <div className="d-flex flex-row justify-content-evenly align-items-center">
                        <h6 className="w-50">&quot;Definition Not Found&quot; dialog:</h6>
                        <select className="form-select w-50" aria-label="&quot;Definition Not Found&quot; dialog"
                                value={String(options.notFoundDialog)}
                                onChange={event => updateOptions({notFoundDialog: event.target.value === 'true'})}>
                            <option value="true">Enabled</option>
                            <option value="false">Disabled</option>
                        </select>
                    </div>
                    <hr/>
                    <div className="d-flex justify-content-center">
                        <button type="button" id="saveOptions"
                                className={`btn save-options ${savingOptions || optionsSaved ? 'btn-ad-primary' : 'btn-ad-accent'}`}
                                onClick={saveOptions}>
                            {!savingOptions && !optionsSaved && <span>Save</span>}
                            {savingOptions && <span>Saving
                                <span className="spinner-border on-right" role="status"
                                      style={{width: 18, height: 18}}/></span>}
                            {optionsSaved && <span>Saved <span className="material-icons on-right">check</span></span>}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/app/homepage/homepage.component.ts
/*
SPDX-Copyright: Copyright (c) Capital One Services,LLC
SPDX-License-Identifier: Apache-2.0

Copyright 2018 Capital One Services, LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 */

import {Component, OnInit, ViewEncapsulation, ChangeDetectionStrategy} from '@angular/core';
import {ConfigurationService} from '../core/configuration/configuration.service';
import {OptionsModel, OptionsModelKeys} from '../models/options.model';
import {DomSanitizer} from '@angular/platform-browser';
import {ConfigModel} from '../models/config.model';

@Component({
    selector: 'app-homepage',
    templateUrl: './homepage.component.html',
    styleUrls: ['./homepage.component.scss'],
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.Eager,
    standalone: false
})
export class HomepageComponent implements OnInit {

    config: ConfigModel;
    options: OptionsModel = new OptionsModel();
    extensionVersion = '';
    slackChannelNativeUrl;

    savingOptions: boolean;
    optionsSaved: boolean;

    constructor(private configurationService: ConfigurationService, private domSanitizer: DomSanitizer) {
    }

    ngOnInit() {
        this.populateConfiguration();
        this.populateOptions();
        this.populateExtensionVersion();
    }

    /**
     * Populates the configuration
     */
    populateConfiguration(): void {
        this.configurationService.getConfiguration().subscribe(
            (config: ConfigModel) => {
                this.config = config;
                // To avoid unsafe prefix for the link
                this.slackChannelNativeUrl = this.domSanitizer.bypassSecurityTrustUrl(this.config.slackChannelLink);
            }
        );
    }

    /**
     * Populates the options
     */
    populateOptions(): void {
        chrome.storage.local.get(OptionsModelKeys,
            (result: any) => {
                this.options = new OptionsModel(result);
                console.log('options', this.options);
            });
    }

    /**
     * Populates the extension version
     */
    populateExtensionVersion(): void {
        this.configurationService.getExtensionVersion()
            .subscribe(version => {
                this.extensionVersion = version;
            });
    }

    saveOptions() {
        this.optionsSaved = false;
        this.savingOptions = true;
        chrome.storage.local.set(this.options, () => {
            /* Unknown issue where callback is extremely slow even after changes
             * have been picked up by content-script, sometimes callback not fired.
             */

            // this.savingOptions = false;
            // this.optionsSaved = true;
        });
        // Fake saving spinner
        setTimeout(() => {
            this.savingOptions = false;
            this.optionsSaved = true;
        }, 2000);
    }

    optionsChanged() {
        this.optionsSaved = false;
        this.savingOptions = false;
    }

}

<!--
SPDX-Copyright: Copyright (c) Capital One Services,LLC
SPDX-License-Identifier: Apache-2.0

Copyright 2018 Capital One Services, LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->

<div id="decoderOptions">
    <div id="optionsContainer">
        <div class="text-center">
            <img id="icon" class="logo" [src]="config?.mainIconPath"/>

            <p id="version">v{{extensionVersion}}</p>
        </div>
        <div class="options-box">
            <div class="options-info">
                <p>
                    Your input makes Acronym Decoder smarter! Please send feedback on wrong/missing definitions or this tool in
                    general to
                    <a href="mailto:{{config?.contactEmail}}">{{config?.contactEmail}}</a>
                </p>
                <p>
                    For more info on Acronym Decoder and how to use it, visit our
                    <a [href]="config?.extensionInfoPageLink" target="_blank" rel="noopener noreferrer">
                        {{config?.extensionInfoPageName}}
                    </a>
                    or join our Slack channel
                    <a [href]="slackChannelNativeUrl">
                        {{config?.slackChannelName}}
                    </a>
                </p>
            </div>
            <hr>
            <h4>Options</h4>
            <hr>
            <div class="option-row">
                <h6 class="option-half">On page lookup:</h6>
                <mat-form-field class="option-half">
                    <mat-select [(value)]="options.lookupEnabled" (valueChange)="optionsChanged()">
                        <mat-option [value]="true">Enabled</mat-option>
                        <mat-option [value]="false">Disabled</mat-option>
                    </mat-select>
                </mat-form-field>
            </div>
            <div class="option-row">
                <h6 class="option-half">Mouse click modifier:</h6>
                <mat-form-field class="option-half">
                    <mat-select [(value)]="options.lookupModifier" (valueChange)="optionsChanged()">
                        <mat-option [value]="0">Only Double Click</mat-option>
                        <mat-option [value]="1">Ctrl + Double Click</mat-option>
                        <mat-option [value]="2">Alt + Double Click</mat-option>
                        <mat-option [value]="3">Command + Double Click</mat-option>
                        <mat-option [value]="4">Ctrl + Alt + Double Click</mat-option>
                    </mat-select>
                </mat-form-field>
            </div>
            <div class="option-row">
                <h6 class="option-half">"Definition Not Found" dialog:</h6>
                <mat-form-field class="option-half">
                    <mat-select [(value)]="options.notFoundDialog" (valueChange)="optionsChanged()">
                        <mat-option [value]="true">Enabled</mat-option>
                        <mat-option [value]="false">Disabled</mat-option>
                    </mat-select>
                </mat-form-field>
            </div>
            <hr>
            <div class="option-actions">
                <button mat-raised-button [color]="savingOptions || optionsSaved ? 'primary' : 'accent'" type="button"
                        id="saveOptions" class="save-options"
                        (click)="saveOptions()">
                    <span *ngIf="!savingOptions && !optionsSaved">Save</span>
                    <span *ngIf="savingOptions">Saving
                        <mat-spinner class="on-right" [diameter]="18" color="accent"></mat-spinner></span>
                    <span *ngIf="optionsSaved">Saved <mat-icon class="on-right">check</mat-icon></span>
                </button>
            </div>
        </div>
    </div>
</div>
