// src/app/lookup/Lookup.tsx
/*
SPDX-Copyright: Copyright (c) Capital One Services,LLC 
SPDX-License-Identifier: Apache-2.0

Copyright 2018 Capital One Services, LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 */

import {LookupModel} from '../models/lookup.model';

export interface LookupProps {
    lookupWord: string;
    definitions: LookupModel[];
}

export function Lookup({lookupWord, definitions}: LookupProps) {
    return (
        <div className="lookup-popup">
            {definitions.length > 0 ? (
                <div>
                    <a className="header">{lookupWord}</a>
                    <ol>
                        {definitions.map((def, i) => (
                            <li key={i}>
                                <p>{def.definition}</p>
                                <ul>
                                    {(def.links ?? []).map((link, j) => (
                                        <li key={j}>{link.name}:{' '}
                                            <a href={link.link} target="_blank" rel="noopener noreferrer">{link.link}</a>
                                        </li>
                                    ))}
                                </ul>
                            </li>
                        ))}
                    </ol>
                </div>
            ) : (
                <div>
                    <p>No definition found</p>
                </div>
            )}
        </div>
    );
}

// src/app/lookup/lookup.component.ts
/*
SPDX-Copyright: Copyright (c) Capital One Services,LLC
SPDX-License-Identifier: Apache-2.0

Copyright 2018 Capital One Services, LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 */

import {ChangeDetectorRef, Component, OnInit, ChangeDetectionStrategy} from '@angular/core';
import {LookupModel} from '../models/lookup.model';

@Component({
    selector: 'app-lookup',
    templateUrl: './lookup.component.html',
    styleUrls: ['./lookup.component.css'],
    changeDetection: ChangeDetectionStrategy.Eager,
    standalone: false
})
export class LookupComponent implements OnInit {

    // These are set in the event-page component
    lookupWord: string;
    definitions: LookupModel[];

    constructor(public changeDetectorRef: ChangeDetectorRef) {
    }

    ngOnInit() {
    }

}

<!--
SPDX-Copyright: Copyright (c) Capital One Services,LLC
SPDX-License-Identifier: Apache-2.0

Copyright 2018 Capital One Services, LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->

<div class="lookup-popup">
  @if (definitions.length > 0) {
    <div>
      <a class="header">{{lookupWord}}</a>
      <ol>
        @for (def of definitions; track def) {
          <li>
            <p>{{def.definition}}</p>
            <ul>
              @for (link of def.links; track link) {
                <li>{{link.name}}:
                  <a [href]="link.link" target="_blank" rel="noopener noreferrer">{{link.link}}</a>
                </li>
              }
            </ul>
          </li>
        }
      </ol>
    </div>
  }
  @if (definitions.length === 0) {
    <div>
      <p>No definition found</p>
    </div>
  }
</div>
